name: Build

on:
  workflow_dispatch:
    inputs:
      versions:
        description: Versions to build/update, empty == all of the missing
        default: ""
  schedule:
    - cron: '0 2 * * 6' # saturday 2am

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to create releases
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3
      - name: Run build itself
        env:
          VERSIONS: ${{ github.event.inputs.versions}}

        run: |
          ./create_releases "$VERSIONS"
      

